<?php


use Nette\Caching\IStorage;
use Nette\Database\Context;
use Nette\Database\Table\ActiveRow;
use Nette\Security\User;

class LanguageManager extends Manager {

    const TABLE = "language",
        COLUMN_ID = "language_id",
        COLUMN_CODE = "code", COLUMN_CODE_LENGTH = 5,

        SETTINGS_DEFAULT_LANGUAGE = "language.default";

    /**
     * @var \Nette\Caching\Cache
     */
    private $codeCache;
    /**
     * @var \Nette\Caching\Cache
     */
    private $idCache;

    protected function init() {
        $cache = new Cache($this->getDefaultStorage(), "language");
        $this->codeCache = $cache->derive("code");
        $this->idCache = $cache->derive("id");
        parent::init(); // TODO: Change the autogenerated stub
    }


    /**
     * @param bool $asObjects
     * @return string[]|Language[]
     */
    public function getAvailableLanguages($asObjects = false): array {
        $data = $this->getDatabase()->table(self::TABLE)->fetchAll();
        $langs = [];
        /** @var ActiveRow $lang */
        foreach ($data as $lang) {
            $langs[] = ($asObjects) ? $this->createFromRow($lang) : $lang[self::COLUMN_CODE];
        }
        return $langs;
    }

    /**
     * @return Language
     * @throws Exception
     */
    public function getDefaultLanguage(): Language {
        $defaultLang = $this->getSettingsManager()->get(self::SETTINGS_DEFAULT_LANGUAGE);

        if (!$defaultLang instanceof Setting || !($language = $this->getById($defaultLang->getValue()))) {
            throw new Exception("DefaultLang not set or doesnt exist");
        }

        return $language;
    }

    public function getByCode(string $langCode): ?Language {
        return $this->codeCache->load($langCode);
    }

    private function createFromRow(ActiveRow $data): Language {
        return new Language(
            $data[self::COLUMN_ID],
            $data[self::COLUMN_CODE]
        );
    }

    public function getById(int $id):?Language {
        return $this->idCache->load($id);
    }

    protected function getBy(array $where):?Language {
        $data = $this->getDatabase()->table(self::TABLE)->where($where)->fetch();

        if ($data instanceof Nette\Database\Table\ActiveRow) {
            return $this->createFromRow($data);
        }
        return null;
    }

    public function rebuildCache() {
        //TODO check rights
        $this->idCache->clean();
        $this->codeCache->clean();
        foreach ($this->getAvailableLanguages(true) as $language) {
            $this->idCache->save($language->getId(), $language);
            $this->codeCache->save($language->getCode(), $language);
        }
    }

    //TODO onAdd add setting homepage for this language
}