INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (1, 'language.default', '1', 0);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (2, 'site.title', 'Nette :)', 0);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (3, 'site.ga', '', 0);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (4, 'site.title_separator', ' | ', 0);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (6, 'site.title', 'Nette in english xd', 1);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (7, 'site.logo', 'img.png', 0);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (8, 'site.logo.alt', 'logo', 0);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (9, 'site.homepage_id', '9', 1);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (10, 'site.title', '', 2);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (11, 'site.homepage_id', '9', 2);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (12, 'site.ga', '', 2);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (13, 'site.logo', '0', 2);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (14, 'site.title_separator', '0', 2);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (17, 'site.ga', '', 1);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (18, 'site.logo', '0', 1);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (19, 'site.title_separator', '', 1);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (20, 'site.favicon', '0', 0);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (21, 'site.favicon', '0', 1);
INSERT INTO `cms-nette`.settings (settings_id, `option`, value, lang_id) VALUES (22, 'site.favicon', '0', 2);