<?php

namespace frontModule;

use ArticlePageControl;
use BasePresenter;
use ContentControl;
use HeaderPageControl;
use Language;
use Nette\Application\BadRequestException;
use Page;
use PageManager;
use SectionPageControl;
use StdClass;
use Tag;

class PagePresenter extends BasePresenter {
    const PARAM_URL = "url",
        PARAM_ID = "page_id";

    /** @var  Page|null */
    private $page;

    public function startup() {
        parent::startup(); // TODO: Change the autogenerated stub
    }


    public function renderDefault() {
        $url = $this->getParameter(self::PARAM_URL);
        $language = $this->getLocaleLanguage()->getId();

        $this->page = $this->getPageManager()->getByUrl($language, (string)$url);
        if($this->page->isHomePage()) $this->redirect(301,"Home",[self::PARAM_URL=>null]);
        $this->prepareTemplate();
    }

    public function actionPermanent() {
        $id = $this->getParameter(self::PARAM_ID);
        $this->page = $this->getPageManager()->getByGlobalId($this->getLocaleLanguage()->getId(), $id);
        $this->prepareTemplate();
    }

    protected function prepareTemplate() {
        $page = $this->page;

        if (!$page instanceof Page)
            $page = $this->getPageManager()->getDefault404();

        $this->template->page = $page;
        $this->payload->title = $page->getTitle();
        $this->template->setFile(__DIR__ . "/templates/Page/default.latte");
    }

    public function renderHome() {
        $language = $this->getLocaleLanguage();
        $pageId = (int)$this->getSettingsManager()->get(PageManager::SETTINGS_HOMEPAGE, $language)->getValue();

        $this->page = $this->getPageManager()->getByGlobalId($language, $pageId);

        $this->prepareTemplate();
    }

    protected
    function getAllowedRoles(): array {
        return \UserManager::ROLES;
    }

    public
    function createComponentContent(string $name): ContentControl {
        return new ContentControl($this, $name);
    }

    /**
     * @param string $name
     * @return ArticlePageControl
     */
    public
    function createComponentArticlePage(string $name): ArticlePageControl {
        return new ArticlePageControl($this, $name);
    }

    public
    function createComponentHeader(string $name): HeaderPageControl {
        return new HeaderPageControl($this->page, $this, $name);
    }

    public
    function createComponentSectionPage(string $name): SectionPageControl {
        return new SectionPageControl($this, $name);
    }
}